# Base stage - setup pnpm and turbo
FROM node:24-alpine AS base

WORKDIR /app

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV CI=true

RUN corepack enable && corepack prepare pnpm@10.28.0 --activate
RUN pnpm add -g turbo
COPY . .
RUN turbo prune @hjaerna/bot --docker


FROM base AS builder

WORKDIR /app

COPY --from=base /app/out/json/ .
# COPY --from=base /app/out/pnpm-lock.yaml ./pnpm-lock.yaml

RUN pnpm install --no-frozen-lockfile

COPY --from=base /app/out/full/ .

# RUN turbo run build


FROM base AS runner

ENV NODE_ENV=production

WORKDIR /app

RUN addgroup --system --gid 1001 bot
RUN adduser --system --uid 1001 bot
USER bot

COPY --from=builder /app/apps/bot ./apps/bot

CMD ["npx", "tsx", "/app/apps/bot/src/index.ts"]
